// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myAutoMapperExample.myContext;

namespace myAutoMapperExample.Migrations
{
    [DbContext(typeof(myDbContext))]
    [Migration("20211011075228_test1")]
    partial class test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("myAutoMapperExample.myPOCO.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 123,
                            AddedDate = new DateTime(2021, 10, 11, 7, 52, 28, 136, DateTimeKind.Utc).AddTicks(7820),
                            Email = "sandeep@gmail.com",
                            IPAddress = "56678",
                            Password = "test123",
                            UserName = "sandeep",
                            modifyDate = new DateTime(2021, 10, 11, 7, 52, 28, 136, DateTimeKind.Utc).AddTicks(8468)
                        },
                        new
                        {
                            Id = 163,
                            AddedDate = new DateTime(2021, 10, 11, 7, 52, 28, 137, DateTimeKind.Utc).AddTicks(9294),
                            Email = "sandeep23@gmail.com",
                            IPAddress = "56678",
                            Password = "test789",
                            UserName = "sandeep karan",
                            modifyDate = new DateTime(2021, 10, 11, 7, 52, 28, 137, DateTimeKind.Utc).AddTicks(9300)
                        });
                });

            modelBuilder.Entity("myAutoMapperExample.myPOCO.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("myAutoMapperExample.myPOCO.UserProfile", b =>
                {
                    b.HasOne("myAutoMapperExample.myPOCO.User", "user")
                        .WithOne("userProfile")
                        .HasForeignKey("myAutoMapperExample.myPOCO.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("myAutoMapperExample.myPOCO.User", b =>
                {
                    b.Navigation("userProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
